=== bmascat/daw-notes/DWLM/Eval1/Prof_material/practicas/XML_XSD_actividades/formula1/equiposFormula1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="formula1">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="equipos" />
        <xs:element ref="pilotos" />
      </xs:sequence>
    </xs:complexType>
    <xs:key name="pertenece">
        <xs:selector xpath=".//piloto" />
        <xs:field xpath="@codigoPiloto" />
    </xs:key>
    <xs:keyref name="relacion" refer="pertenece">
        <xs:selector xpath=".//pilota" />
        <xs:field xpath="@id" />
    </xs:keyref>
  </xs:element>
  <xs:element name="equipos">
      <xs:complexType>
          <xs:sequence>
              <xs:element ref="equipo" maxOccurs="unbounded" />
          </xs:sequence>
      </xs:complexType>
  </xs:element>
  <xs:element name="equipo">
      <xs:complexType>
          <xs:sequence>
              <xs:element name="nombre" type="xs:string" />
              <xs:element ref="temporada" maxOccurs="unbounded" />
          </xs:sequence>
      </xs:complexType>
  </xs:element>
  <xs:element name="temporada">
      <xs:complexType>
          <xs:sequence>
              <xs:element name="año" type="xs:string" />
              <xs:element name="pilota" maxOccurs="2">
                  <xs:complexType>
                      <xs:attribute name="id" type="xs:unsignedByte" />
                  </xs:complexType>
              </xs:element>
          </xs:sequence>
      </xs:complexType>
  </xs:element>
  <xs:element name="pilotos">
      <xs:complexType>
          <xs:sequence>
              <xs:element ref="piloto" maxOccurs="unbounded"/>
          </xs:sequence>
      </xs:complexType>
  </xs:element>
  <xs:element name="piloto">
      <xs:complexType>
          <xs:sequence>
              <xs:element name="nombre" type="xs:string" />
              <xs:element name="edad" type="xs:integer" />
          </xs:sequence>
          <xs:attribute name="codigoPiloto" type="xs:unsignedByte" />
      </xs:complexType>
  </xs:element>
</xs:schema>

=== bmascat/daw-notes/DWLM/Eval1/Prof_material/practicas/XML_XSD_actividades/formula1/equiposFormula1.xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<formula1 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="equiposFormula1.xsd">
  <equipos>
    <equipo>
      <nombre>Mercedes-AMG Petronas F1 Team</nombre>
      <temporada>
        <año>2020</año>
        <pilota id="1"/>
        <pilota id="2"/>
      </temporada>
      <temporada>
        <año>2021</año>
        <pilota id="1"/>
        <pilota id="2"/>
      </temporada>
    </equipo>
    <equipo>
      <nombre>Red Bull Racing Honda</nombre>
      <temporada>
        <año>2019</año>
        <pilota id="6"/>
        <pilota id="4"/>
      </temporada>
      <temporada>
        <año>2020</año>
        <pilota id="3"/>
        <pilota id="4"/>
      </temporada>
      <temporada>
        <año>2021</año>
        <pilota id="3"/>
        <pilota id="5"/>
      </temporada>
    </equipo>
    <equipo>
      <nombre>Scuderia Ferrari</nombre>
      <temporada>
        <año>2020</año>
        <pilota id="6"/>
        <pilota id="7"/>
      </temporada>
      <temporada>
        <año>2021</año>
        <pilota id="7"/>
        <pilota id="6"/>
      </temporada>
    </equipo>
  </equipos>
  <pilotos>
    <piloto codigoPiloto="1">
      <nombre>Lewis Hamilton</nombre>
      <edad>37</edad>
    </piloto>
    <piloto codigoPiloto="2">
      <nombre>Valtteri Bottas</nombre>
      <edad>32</edad>
    </piloto>
    <piloto codigoPiloto="3">
      <nombre>Max Verstappen</nombre>
      <edad>24</edad>
    </piloto>
    <piloto codigoPiloto="4">
      <nombre>Alexander Albon</nombre>
      <edad>25</edad>
    </piloto>
    <piloto codigoPiloto="5">
      <nombre>Sergio Pérez</nombre>
      <edad>31</edad>
    </piloto>
    <piloto codigoPiloto="6">
      <nombre>Sebastian Vettel</nombre>
      <edad>34</edad>
    </piloto>
    <piloto codigoPiloto="7">
      <nombre>Charles Leclerc</nombre>
      <edad>23</edad>
    </piloto>
    <piloto codigoPiloto="8">
      <nombre>Carlos Sainz Jr.</nombre>
      <edad>27</edad>
    </piloto>
  </pilotos>
</formula1>
